import type {
  StudioCodegen,
  StudioFlow,
  StudioNode,
  StudioRun,
  StudioExecutionTraceStep,
} from '@paddie-studio/types';

export interface RuntimeExecuteRequest {
  flow: StudioFlow;
  trigger: 'manual' | 'webhook' | 'chat';
  input?: unknown;
}

export interface RuntimeExecuteResponse {
  run: StudioRun;
}

export interface RuntimeCodegenRequest {
  flow: StudioFlow;
  language: 'javascript' | 'python';
  webhookUrl: string;
}

export interface RuntimeCodegenProvider {
  generate(request: RuntimeCodegenRequest): StudioCodegen;
}

export function createTraceSkeleton(flow: StudioFlow): StudioExecutionTraceStep[] {
  return flow.nodes.map((node, index) => ({
    step: index + 1,
    nodeId: node.id,
    nodeType: node.type,
    status: 'failed',
    startedAt: new Date().toISOString(),
    endedAt: new Date().toISOString(),
    durationMs: 0,
    dispatches: [],
  }));
}

export function createPendingRun(flow: StudioFlow, trigger: RuntimeExecuteRequest['trigger'], input?: unknown): StudioRun {
  const now = new Date().toISOString();
  return {
    id: `studio_run_${Date.now()}`,
    flowId: flow.id,
    status: 'success',
    triggeredBy: trigger,
    triggerPayload: input ?? {},
    output: null,
    nodeResults: {},
    executionTrace: createTraceSkeleton(flow),
    startedAt: now,
    endedAt: now,
    durationMs: 0,
  };
}

export function listFlowNodesByType(flow: StudioFlow, type: StudioNode['type']): StudioNode[] {
  return flow.nodes.filter((node) => node.type === type);
}

export class RuntimeCodegenService {
  private static instance: RuntimeCodegenService;

  private constructor() {}

  static getInstance(): RuntimeCodegenService {
    if (!RuntimeCodegenService.instance) {
      RuntimeCodegenService.instance = new RuntimeCodegenService();
    }
    return RuntimeCodegenService.instance;
  }

  generate(
    flow: StudioFlow,
    language: 'javascript' | 'python',
    webhookUrl: string
  ): StudioCodegen {
    if (language === 'python') {
      return {
        language,
        code: this.generatePython(flow, webhookUrl),
        webhookUrl,
      };
    }

    return {
      language: 'javascript',
      code: this.generateJavascript(flow, webhookUrl),
      webhookUrl,
      stackblitzProject: this.buildStackblitzProject(flow, webhookUrl),
    };
  }

  private generateJavascript(flow: StudioFlow, webhookUrl: string): string {
    return `/**
 * Generated by Studio Runtime
 * Flow: ${flow.name}
 * Webhook: ${webhookUrl}
 */

const WEBHOOK_URL = "${webhookUrl}";

export async function runStudioFlow(payload = {}) {
  const response = await fetch(WEBHOOK_URL, {
    method: "POST",
    headers: {
      "content-type": "application/json"
    },
    body: JSON.stringify(payload)
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(\`Studio webhook failed (\${response.status}): \${errorText}\`);
  }

  return response.json();
}

const samplePayload = {
  event: "studio-demo",
  timestamp: new Date().toISOString()
};

runStudioFlow(samplePayload)
  .then((result) => {
    console.log("Studio flow output:");
    console.log(JSON.stringify(result, null, 2));
  })
  .catch((error) => {
    console.error("Studio flow error:", error.message);
  });
`;
  }

  private generatePython(flow: StudioFlow, webhookUrl: string): string {
    return `"""
Generated by Studio Runtime
Flow: ${flow.name}
Webhook: ${webhookUrl}
"""

import requests
from datetime import datetime

WEBHOOK_URL = "${webhookUrl}"


def run_studio_flow(payload: dict) -> dict:
    response = requests.post(WEBHOOK_URL, json=payload, timeout=20)
    response.raise_for_status()
    return response.json()


if __name__ == "__main__":
    sample_payload = {
        "event": "studio-demo",
        "timestamp": datetime.utcnow().isoformat() + "Z"
    }

    try:
        result = run_studio_flow(sample_payload)
        print("Studio flow output:")
        print(result)
    except requests.HTTPError as error:
        print(f"Studio webhook failed: {error}")
`;
  }

  private buildStackblitzProject(flow: StudioFlow, webhookUrl: string): StudioCodegen['stackblitzProject'] {
    return {
      title: `Studio Demo - ${flow.name}`,
      description: 'Generated Studio webhook client',
      files: {
        'index.js': this.generateJavascript(flow, webhookUrl),
        'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Studio Demo - ${flow.name}</title>
    <style>
      body {
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
        background: #0f172a;
        color: #e2e8f0;
        margin: 0;
        padding: 24px;
      }
      pre {
        background: #020617;
        border: 1px solid #334155;
        border-radius: 10px;
        padding: 16px;
        overflow: auto;
      }
      .note {
        margin-bottom: 16px;
        padding: 12px;
        border-radius: 10px;
        border: 1px solid #334155;
        background: #111827;
      }
    </style>
  </head>
  <body>
    <h1>Studio Generated Client</h1>
    <div class="note">
      This demo executes the Studio webhook for flow "<strong>${flow.name}</strong>".
    </div>
    <pre id="output">Running...</pre>
    <script type="module">
      import { runStudioFlow } from './index.js';

      const output = document.getElementById('output');
      runStudioFlow({
        event: 'stackblitz-demo',
        timestamp: new Date().toISOString()
      })
      .then((result) => {
        output.textContent = JSON.stringify(result, null, 2);
      })
      .catch((error) => {
        output.textContent = 'Error: ' + error.message;
      });
    </script>
  </body>
</html>`,
        'package.json': `{
  "name": "studio-generated-flow-client",
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "start": "vite"
  },
  "devDependencies": {
    "vite": "^7.0.0"
  }
}`,
      },
    };
  }
}
